# Generated by Django 6.0.5 on 2026-07-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address attempted to login', max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of login attempt')),
                ('success', models.BooleanField(default=False, help_text='Whether login was successful')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When login was attempted')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', '-attempted_at'], name='account_log_email_f17ab7_idx'), models.Index(fields=['ip_address', '-attempted_at'], name='account_log_ip_addr_836a82_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup', 'User Signup'), ('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_changed', 'Email Changed'), ('email_verified', 'Email Verified'), ('profile_updated', 'Profile Updated'), ('account_deleted', 'Account Deleted')], help_text='Type of action performed', max_length=30)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address where action originated')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional JSON details about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when action occurred')),
                ('user', models.ForeignKey(help_text='User whose action is being logged', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_use_user_id_7df4fa_idx'), models.Index(fields=['action'], name='account_use_action_74ce79_idx')],
            },
        ),
    ]
