# Generated by Django 6.0.5 on 2026-07-25 13:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Good'), (3, '⭐⭐⭐ Average'), (2, '⭐⭐ Poor'), (1, '⭐ Terrible')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the product the customer uploaded with their review', null=True, upload_to='reviews/')),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The specific order this review is tied to', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='product_rev_product_a2a808_idx'), models.Index(fields=['customer'], name='product_rev_custome_6fc6ed_idx')],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
