# Generated by Django 6.0.5 on 2026-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of the product the customer uploaded with their review', null=True, upload_to='reviews/'),
        ),
    ]
