# Generated by Django 6.0.5 on 2026-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productreview_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
