# Generated by Django 6.0.5 on 2026-07-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city_order_country_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Upload bank transfer receipt or payment proof', null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
