# Generated by Django 6.0.5 on 2026-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_receipt_order_receipt_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('Received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
