# Generated by Django 6.0.5 on 2026-08-04 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('confirmation_message', models.TextField(blank=True, default='You have selected Store Pickup. Your order will be prepared for collection at our store. We will contact you when it is ready.', help_text='Shown to the customer at checkout when they select this location.')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive locations won't be offered as a pickup option at checkout.")),
            ],
            options={
                'verbose_name': 'Pickup Location',
                'verbose_name_plural': 'Pickup Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 for pickup orders. Currently a flat placeholder fee for delivery.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Store Pickup')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text="Set only when fulfillment_method is 'pickup'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pickuplocation'),
        ),
    ]
