# Generated by Django 6.0.5 on 2026-08-05 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pickuplocation_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PickupOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pickup Order',
                'verbose_name_plural': 'Pickup Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Currently always 0 — delivery fee is arranged directly with the customer.', max_digits=10),
        ),
    ]
