# Generated by Django 6.0.6 on 2026-08-16 10:22

from django.db import migrations
# This file was generated empty by:
#   python manage.py makemigrations orders --empty --name backfill_order_status_history
# Keep the auto-generated `dependencies` list Django wrote for you at the
# top of the real file — only the `operations` list below needs replacing
# with this content.

from django.db import migrations


def backfill_status_history(apps, schema_editor):
    """
    Existing orders have no history — we can't know the exact times they
    moved through each status, since that wasn't tracked before. Rather
    than inventing fake intermediate timestamps, this creates the two data
    points we can actually stand behind:
      1. Every order really did start as 'pending' at order.created_at
         (checkout always creates orders with that default).
      2. If the order has since moved to a different status, one more
         entry is added at order.updated_at — the best available
         approximation of when that happened, since Order doesn't track
         per-field change timestamps.
    This means older orders show a simpler 2-point timeline instead of the
    full multi-stage one — accurate to what we actually know, not padded
    out to look more granular than the data supports.
    """
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')

    for order in Order.objects.all():
        OrderStatusHistory.objects.create(
            order=order,
            status='pending',
            note='Backfilled from existing order data (exact original timestamp unknown).',
            changed_by=None,
            created_at=order.created_at,
        )
        if order.status != 'pending':
            OrderStatusHistory.objects.create(
                order=order,
                status=order.status,
                note='Backfilled from existing order data — timestamp approximated '
                     'from the order\'s last-updated time, not the actual transition time.',
                changed_by=None,
                created_at=order.updated_at,
            )


def noop_reverse(apps, schema_editor):
    # Nothing to reverse — fine to leave backfilled history rows in place
    # if this migration is ever rolled back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_orderstatushistory'),
    ]

    operations = [
        migrations.RunPython(backfill_status_history, noop_reverse),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_orderstatushistory'),
    ]

    operations = [
        migrations.RunPython(backfill_status_history, noop_reverse),
    ]
