# Generated by Django 6.0.6 on 2026-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_backfill_order_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the customer confirmed they received this order.', null=True),
        ),
    ]
